# Generated by Django 3.2.25 on 2025-01-12 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="reg",
            options={"verbose_name_plural": "Registration numbers"},
        ),
    ]
