# Generated by Django 3.2.25 on 2025-01-30 15:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_reg_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='reg',
        ),
        migrations.AddField(
            model_name='stock',
            name='reg_number',
            field=models.CharField(default='DEFAULT_REG', max_length=254, unique=True, validators=[django.core.validators.RegexValidator(message='Registration number must be alphanumeric', regex='^[A-Za-z0-9]*$')]),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Reg',
        ),
    ]
