# Generated by Django 3.2.25 on 2025-02-03 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_auto_20250202_1555"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stock",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
